

<?php $__env->startSection('title', 'Generate Course Badge'); ?>

<?php $__env->startSection('content'); ?>
<div class="container mt-5 mb-5">
  <div class="card shadow border-0">
    <div class="card-body">
            <?php if(session('success')): ?>
          <div class="alert alert-success alert-dismissible fade show" role="alert">
              <?php echo e(session('success')); ?>

              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
      <?php endif; ?>

      <?php if(session('error')): ?>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <?php echo e(session('error')); ?>

              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
      <?php endif; ?>
      <h3 class="text-primary mb-4">Course Completion & Badge Generation</h3>
      

      <!-- 🔹 Unified Search Form -->
      <form id="searchForm" class="row g-3 mb-4">
        <?php echo csrf_field(); ?>
        <div class="col-md-3">
          <label class="form-label">Student ID / NIC</label>
          <input type="text" id="student_id" name="student_id" class="form-control" placeholder="Enter Student ID or NIC">
        </div>

        <div class="col-md-3">
          <label class="form-label">Course</label>
          <select id="courseSelect" name="course_id" class="form-select">
            <option value="">All Courses</option>
            <?php $__currentLoopData = \App\Models\Course::orderBy('course_name')->get(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $course): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
              <option value="<?php echo e($course->course_id); ?>"><?php echo e($course->course_name); ?></option>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
          </select>
        </div>

        <div class="col-md-3">
          <label class="form-label">Intake</label>
          <select id="intakeSelect" name="intake_id" class="form-select">
            <option value="">All Intakes</option>
          </select>
        </div>

        <div class="col-md-2">
          <label class="form-label">Mode</label>
          <select id="modeSelect" name="mode" class="form-select">
            <option value="">All</option>
            <option value="Online">Online</option>
            <option value="Physical">Physical</option>
          </select>
        </div>

        <div class="col-md-1 d-flex align-items-end">
          <button id="searchBtn" class="btn btn-primary w-auto" type="submit">
            <span class="spinner-border spinner-border-sm d-none" id="searchSpinner" role="status"></span>
            <span id="searchText">Search</span>
          </button>
        </div>
      </form>

      <div class="text-end mb-3">
        <button class="btn btn-outline-secondary btn-sm" id="clearFilters">
          <i class="ti ti-refresh me-1"></i> Clear Filters
        </button>
      </div>

      <!-- 📋 Results -->
      <div id="resultSection" style="display:none;">
        <h5 class="fw-bold text-secondary mb-3">Search Results</h5>
        <table class="table table-bordered align-middle">
          <thead class="table-light">
            <tr>
              <th>#</th>
              <th>Student</th>
              <th>Course</th>
              <th>Type</th>
              <th>Intake</th>
              <th>Mode</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody id="courseRows"></tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- 🔹 Certificate Modal -->
<div class="modal fade" id="viewCertModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content border-0 shadow-lg">
      <div class="modal-header bg-primary text-white">
        <h5 class="modal-title"><i class="ti ti-certificate me-2"></i>Certificate Details</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body" id="viewCertBody">
        <div class="text-center p-5">
          <div class="spinner-border text-primary"></div>
        </div>
      </div>
      <div class="modal-footer d-flex justify-content-between">
        <small class="text-muted fst-italic">Generated by Nebula Institute of Technology</small>
        <a id="viewCertLink" href="#" target="_blank" class="btn btn-outline-primary">
          <i class="ti ti-external-link"></i> View Certificate
        </a>
      </div>
    </div>
  </div>
</div>
<style>
  .error-message {
    position: fixed;
    top: 20px;
    right: 20px;
    z-index: 9999;
    background: linear-gradient(135deg, #dc3545, #e74c3c);
    color: white;
    padding: 15px 20px;
    border-radius: 10px;
    box-shadow: 0 4px 15px rgba(220, 53, 69, 0.3);
    font-weight: 500;
    font-size: 14px;
    max-width: 400px;
    transform: translateX(100%);
    transition: transform 0.3s ease-in-out;
    border-left: 4px solid #fff;
}

.error-message.show {
    transform: translateX(0);
}

.error-message .error-icon {
    margin-right: 10px;
    font-size: 18px;
}
</style>
<script>
  // ---------- Notifications ----------
function showSuccessMessage(message){
  document.querySelectorAll('.success-message,.error-message').forEach(m=>m.remove());
  const n=document.createElement('div'); n.className='success-message';
  n.innerHTML=`<i class="ti ti-check-circle success-icon"></i>${message}`;
  document.body.appendChild(n); setTimeout(()=>n.classList.add('show'),100);
  setTimeout(()=>{n.classList.remove('show'); setTimeout(()=>n.remove(),300)},4000);
}
function showErrorMessage(message){
  document.querySelectorAll('.success-message,.error-message').forEach(m=>m.remove());
  const n=document.createElement('div'); n.className='error-message';
  n.innerHTML=`<i class="ti ti-alert-circle error-icon"></i>${message}`;
  document.body.appendChild(n); setTimeout(()=>n.classList.add('show'),100);
  setTimeout(()=>{n.classList.remove('show'); setTimeout(()=>n.remove(),300)},5000);
}

/* -------------------------------
   🔹 Dynamic Intake Dropdown
--------------------------------*/
document.getElementById('courseSelect').addEventListener('change', async e => {
  const courseId = e.target.value;
  const intakeSelect = document.getElementById('intakeSelect');
  intakeSelect.innerHTML = '<option>Loading...</option>';

  if (!courseId) {
    intakeSelect.innerHTML = '<option value="">All Intakes</option>';
    return;
  }

  try {
    const res = await fetch(`/api/intakes-by-course/${courseId}`);
    const data = await res.json();
    intakeSelect.innerHTML = '<option value="">All Intakes</option>';
    data.forEach(intake => {
      intakeSelect.innerHTML += `<option value="${intake.intake_id}">${intake.batch} - ${intake.location}</option>`;
    });
  } catch (err) {
    intakeSelect.innerHTML = '<option value="">Error loading intakes</option>';
  }
});

/* -------------------------------
   🔹 Clear Filters
--------------------------------*/
document.getElementById('clearFilters').addEventListener('click', () => {
  document.getElementById('student_id').value = '';
  document.getElementById('courseSelect').value = '';
  document.getElementById('intakeSelect').innerHTML = '<option value="">All Intakes</option>';
  document.getElementById('modeSelect').value = '';
  document.getElementById('courseRows').innerHTML = '';
  document.getElementById('resultSection').style.display = 'none';
});

/* -------------------------------
   🔹 Unified Search Function
--------------------------------*/
document.getElementById('searchForm').addEventListener('submit', async e => {
  e.preventDefault();
  const btn = document.getElementById('searchBtn');
  const spin = document.getElementById('searchSpinner');
  const text = document.getElementById('searchText');
  btn.disabled = true; spin.classList.remove('d-none'); text.textContent = 'Searching...';

  const payload = {
    student_id: document.getElementById('student_id').value.trim(),
    course_id: document.getElementById('courseSelect').value,
    intake_id: document.getElementById('intakeSelect').value,
    mode: document.getElementById('modeSelect').value
  };

  const route = payload.student_id ? '<?php echo e(route("badges.search")); ?>' : '<?php echo e(route("badges.searchByCourse")); ?>';

  const res = await fetch(route, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': '<?php echo e(csrf_token()); ?>' },
    body: JSON.stringify(payload)
  });
  const data = await res.json();
  if (!data.success) {
    showErrorMessage(data.message);
} 

// In your markComplete function:
if (!data.success) {
    showErrorMessage(data.message);
}

// In your cancelBadge function:
if (!data.success) {
    showErrorMessage(data.message);
}
  else renderResults(data.courses || data.data);

  btn.disabled = false; spin.classList.add('d-none'); text.textContent = 'Search';
});

/* -------------------------------
   🔹 Render Results
--------------------------------*/
function renderResults(items) {
  const table = document.getElementById('courseRows');
  table.innerHTML = '';

  if (!items?.length) {
    table.innerHTML = `<tr><td colspan="8" class="text-center text-muted p-3">No records found.</td></tr>`;
    document.getElementById('resultSection').style.display = 'block';
    return;
  }

  items.forEach((r, i) => {
    const student = r.student?.full_name || r.student?.name_with_initials || '-';
    const course = r.course?.course_name || '-';
    const type = r.course?.course_type || '-';
    const intake = r.intake?.batch || '-';
    const mode = r.intake?.intake_mode || '-';
    const status = r.status || '-';
    const badgeCode = r.badge?.verification_code;
    const badgeId = r.badge?.id;
    const allow = (type === 'certificate' && mode === 'Online');

    let action = '';
    if (allow) {
      if (status === 'Completed') {
        if (badgeCode) {
          action = `
            <button class="btn btn-info btn-sm me-2" onclick="viewCertificate('${badgeCode}')">
              <i class='ti ti-eye'></i> View
            </button>
            <button class="btn btn-danger btn-sm" onclick="cancelBadge(${badgeId}, ${r.id}, this)">
              <i class='ti ti-trash'></i> Cancel
            </button>`;
        } else {
          action = `
            <button class="btn btn-secondary btn-sm me-2" disabled><i class='ti ti-badge'></i> Badge Missing</button>
            <button class="btn btn-danger btn-sm" onclick="cancelBadge(null, ${r.id}, this)"><i class='ti ti-trash'></i> Cancel</button>`;
        }
      } else {
        action = `
          <button class="btn btn-success btn-sm" onclick="markComplete(${r.id}, this)">
            <i class='ti ti-badge'></i> Mark Completed & Generate Badge
          </button>`;
      }
    } else {
      action = '<span class="text-muted">Not Eligible</span>';
    }

    table.innerHTML += `
      <tr id="row-${r.id}">
        <td>${i + 1}</td>
        <td>${student}</td>
        <td>${course}</td>
        <td>${type}</td>
        <td>${intake}</td>
        <td>${mode}</td>
        <td id="status-${r.id}">${status}</td>
        <td id="action-${r.id}">${action}</td>
      </tr>`;
  });

  document.getElementById('resultSection').style.display = 'block';
}

/* -------------------------------
   🔹 Mark Complete (Row Update Only)
--------------------------------*/
async function markComplete(id, btn) {
  if (!confirm('Mark this course as completed and generate a badge?')) return;

  btn.disabled = true;
  btn.innerHTML = `<span class="spinner-border spinner-border-sm"></span> Processing...`;

  const res = await fetch('<?php echo e(route("badges.complete")); ?>', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': '<?php echo e(csrf_token()); ?>' },
    body: JSON.stringify({ id })
  });
  const data = await res.json();

  if (data.success) {
    const rowStatus = document.getElementById(`status-${id}`);
    const rowAction = document.getElementById(`action-${id}`);
    rowStatus.innerHTML = `<span class="text-success fw-bold">Completed</span>`;
    rowAction.innerHTML = `
      <button class="btn btn-info btn-sm me-2" onclick="viewCertificate('${data.verification_url.split('/').pop()}')">
        <i class='ti ti-eye'></i> View
      </button>
      <button class="btn btn-danger btn-sm" onclick="cancelBadge(null, ${id}, this)">
        <i class='ti ti-trash'></i> Cancel
      </button>`;

    // Success flash effect
    const tr = document.getElementById(`row-${id}`);
    tr.classList.add('table-success');
    setTimeout(() => tr.classList.remove('table-success'), 1200);
  } else {
    alert(data.message);
  }

  btn.disabled = false;
  btn.innerHTML = `<i class='ti ti-badge'></i> Mark Completed & Generate Badge`;
}

/* -------------------------------
   🔹 Cancel Badge
--------------------------------*/
async function cancelBadge(badgeId, registrationId, btn) {
  if (!confirm('Cancel this certificate?')) return;
  btn.disabled = true;
  btn.innerHTML = `<span class="spinner-border spinner-border-sm"></span>`;

  const res = await fetch('<?php echo e(route("badges.cancel")); ?>', {
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': '<?php echo e(csrf_token()); ?>' },
    body: JSON.stringify({ badge_id: badgeId, registration_id: registrationId })
  });
  const data = await res.json();

  if (data.success) {
    document.getElementById(`status-${registrationId}`).innerHTML = `<span class="text-warning fw-bold">Pending</span>`;
    document.getElementById(`action-${registrationId}`).innerHTML = `
      <button class="btn btn-success btn-sm" onclick="markComplete(${registrationId}, this)">
        <i class='ti ti-badge'></i> Mark Completed & Generate Badge
      </button>`;
  } else {
    alert(data.message);
  }
}

/* -------------------------------
   🔹 View Certificate
--------------------------------*/
async function viewCertificate(code) {
  const body = document.getElementById('viewCertBody');
  const link = document.getElementById('viewCertLink');
  body.innerHTML = `<div class="text-center p-5"><div class="spinner-border text-primary"></div></div>`;
  const res = await fetch(`/badges/details/${code}`);
  const html = await res.text();
  body.innerHTML = html;
  link.href = `/verify-badge/${code}`;
  new bootstrap.Modal(document.getElementById('viewCertModal')).show();
}
</script>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('inc.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH D:\SLT\Welisara\Nebula\resources\views/badges/generate.blade.php ENDPATH**/ ?>